=== DoDAO-io/dodao-academy-processor/src/timelines/validation/schemas/timelineSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "excerpt": {
      "type": "string"
    },
    "content": {
      "type": "string"
    },
    "thumbnail": {
      "type": "string"
    },
    "created": {
      "type": "string"
    },
    "events": {
      "type": "array",
      "items": {
        "$ref": "/TimelineEventSchema"
      }

    },
    "publishStatus": {
      "type": "string"
    },
    "admins": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "tags": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "priority": {
      "type": "integer"
    }
  },
  "required": [
    "admins",
    "id",
    "name",
    "excerpt",
    "content",
    "created",
    "publishStatus",
    "events",
    "priority",
    "tags"
  ],
  "additionalProperties": false
}

=== DoDAO-io/dodao-academy-processor/test/dummy-academy/generated/timelines/main/json/governance-timeline.json
{
  "id": "aave-governance-timeline",
  "name": "AAVE Governance Timeline",
  "excerpt": "Captures timeline of all the governance updates",
  "content": "Captures timeline of all the governance updates",
  "thumbnail": "ipfs://QmNd8S5Z9T8cWv95UUjn5fYR1wU8nLWjeHzXoRC5oVcVe8",
  "created": "2022-11-15T20:00:13.043Z",
  "publishStatus": "Live",
  "priority": 50,
  "admins": [],
  "tags": [],
  "events": [
    {
      "name": "Some Event 1",
      "uuid": "event-1",
      "date": "2022-11-15T20:00:13.043Z",
      "excerpt": "Excerpt",
      "content": "Some more details"
    },
    {
      "name": "Some Event 2",
      "uuid": "event-2",
      "date": "2022-10-15T20:00:13.043Z",
      "excerpt": "Excerpt",
      "content": "Some more details"
    },
    {
      "name": "Some Event 3",
      "uuid": "event-3",
      "date": "2022-09-15T20:00:13.043Z",
      "excerpt": "Excerpt",
      "content": "Some more details"
    },
    {
      "name": "Some Event 4",
      "uuid": "event-4",
      "date": "2022-08-15T20:00:13.043Z",
      "excerpt": "Excerpt",
      "content": "Some more details"
    },
    {
      "name": "Some Event 5",
      "uuid": "event-5",
      "date": "2022-07-15T20:00:13.043Z",
      "excerpt": "Excerpt",
      "content": "Some more details"
    }
  ]
}
